### ISSUE TITLE
Cannot close Action Sheet by clicking outside of its bounds

### ISSUE THREAD

**Issue by schlaup** [akiran/react-foundation-apps#10]
In Foundation for Apps demo (documentation) I can close an Action Sheet by clicking on the background.

In your implementation it does not work. I have to click on the same button that opened the Action Sheet to close it again.

Is this a problem with the Demo code or with the React implementation of Foundation for Apps?

**Comment by akiran** [comment]
Yes, I just noticed that.
I will fix it soon

**Comment by amarnus** [comment]
+1

**Comment by georgwaechter** [comment]
+1
