### ISSUE TITLE
Cannot find module "react-foundation-apps/lib/modal"

### ISSUE THREAD

**Issue by MikaelLarsson** [akiran/react-foundation-apps#18]
Trying to import this package but console says:
Uncaught Error: Cannot find module "react-foundation-apps/lib/modal"

When i use var Modal = require('react-foundation-apps/lib/modal/index.jsx');
it says:
(on line 48) Unexpected token <
You may need an appropriate loader to handle this file type.

I'm using webpack and I added the .jsx extension to the config file. (Don't know if that has to do with anything though).

Thanks

**Comment by MikaelLarsson** [comment]
Solved it by fiddling with the loaders in webpack.config.js

**Comment by nerdgrass** [comment]
@MikaelLarsson How is your webpack configured? I'm running into the same issue.

**Comment by MikaelLarsson** [comment]
I had this config earlier: 
```javascript
loaders: [
    {
         test: /\.js|jsx$/,
         exclude: /node_modules/,
         loader: 'react-hot!jsx-loader?harmony'
    }
]
```
I just removed the 'exclude' variable and it worked (someone else set up this config). I don't know why you would want to exclude /node_modules in the first place though..?

**Comment by nerdgrass** [comment]
Probably to speed up webpack - the require should pull in the stuff you need, and having webpack process all your NPM modules every time you press save (assuming you have a live reload server) would slow it down somewhat to significantly, depending on the size of your project.

That being said, with other react components I've required I haven't had this issue and I'm working on a project large enough that webpack really can't go through every node module. :(

**Comment by akiran** [comment]
@nerdgrass In next release I will provide the jsx to js transformed files in the lib folder to fix this problem

**Comment by nerdgrass** [comment]
That's awesome news! Thanks so much :)

**Comment by AnthonyRinaldi** [comment]
I'm running into this same issue. I'm not using Webpack, just Browserify/Reactify.
