### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by MikaelLarsson** [akiran/react-foundation-apps#19]
I ran the `bower install foundation-apps --save` command but no styling appears. I'm trying to use the Modal component. It appears on the page but with no styling applied. What can I have missed? Could it be something with webpack?

I also ran `bower install foundation-apps` even though it is already added as a dependency but for no luck. 

Please help a noob.

**Comment by MikaelLarsson** [comment]
Am I missing a SASS loader? I tried to install sass-loader and add: 
`loaders: [
   {
      test: /\.scss$/,
      loader: "style!css!sass"
   },
]`
to webpack.config.js but that didn't help.

Please give me a hint of what could be wrong.

**Comment by akiran** [comment]
You have to add css link in you html
<link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/zurb/foundation-apps-1.1.0.min.css>

**Comment by MikaelLarsson** [comment]
Thanks a lot
