### ISSUE TITLE
Cant include component by their path

### ISSUE THREAD

**Issue by dipdipdip84** [akiran/react-foundation-apps#9]
Hello,

Tried to add 
var Offcanvas = require('react-foundation-apps/lib/trigger');

But it cant find it, I have to specify index.jsx but then in this component you also include 
var PopupToggle = require('../popup/toggle');
And browserify cant find it.

**Comment by akiran** [comment]
It is working well with webpack. It should also work with browserify.

Are you able to import other components ?

I think you should add option to include jsx extension in your browserify
command or config.

**Comment by dipdipdip84** [comment]
I am using this yeoman generator : https://github.com/larsonjj/generator-yeogurt

And I am far from being an expert of all these grunt and browserify tasks... :s

**Comment by dipdipdip84** [comment]
ok I manage to fix it in browserify grunt config file :+1:
